export const Skills = [
    "javascript",
    "next.js",
    "react.js",
    "react native",
    "node.js",
    "express.js",
    "firebase",
    "supabase",
    "mongo db",
    "mysql",
    "motion",
    "tailwind css",
    "git",
    "github",
    "vscode",
    "antigravity",
]